// Base d'aliments de départ (valeurs pour 100 g). Modifiable dans Profil > Mes aliments.
export const FOODS = [
  {"id": "poulet-cuit", "name": "Blanc de poulet cuit", "cat": "Protéines", "kcal": 151, "p": 29, "c": 0, "f": 3},
  {"id": "boeuf-hache-extra-maigre", "name": "Bœuf haché extra maigre cuit", "cat": "Protéines", "kcal": 149, "p": 25, "c": 0, "f": 4.6},
  {"id": "steak-hache-5", "name": "Steak haché 5 % MG (cru)", "cat": "Protéines", "kcal": 125, "p": 20, "c": 0, "f": 5, "unit": "steak", "unitG": 100},
  {"id": "steak-hache-3", "name": "Steak haché 3 % MG (cru)", "cat": "Protéines", "kcal": 115, "p": 22, "c": 0, "f": 3, "unit": "steak", "unitG": 100},
  {"id": "dinde-hachee", "name": "Dinde hachée maigre cuite", "cat": "Protéines", "kcal": 152, "p": 19, "c": 0, "f": 7},
  {"id": "thon-naturel", "name": "Thon au naturel égoutté", "cat": "Protéines", "kcal": 116, "p": 25.5, "c": 0, "f": 0.8, "unit": "boîte", "unitG": 93, "aliases": ["thon"]},
  {"id": "cabillaud", "name": "Cabillaud cuit", "cat": "Protéines", "kcal": 105, "p": 22.8, "c": 0, "f": 0.9},
  {"id": "eglefin", "name": "Églefin (haddock) cuit", "cat": "Protéines", "kcal": 112, "p": 24.2, "c": 0, "f": 0.9, "aliases": ["haddock"]},
  {"id": "pangasius", "name": "Pangasius cuit", "cat": "Protéines", "kcal": 118, "p": 22, "c": 0, "f": 2.6},
  {"id": "saumon", "name": "Saumon cuit", "cat": "Protéines", "kcal": 182, "p": 25.4, "c": 0, "f": 8.1},
  {"id": "truite", "name": "Truite cuite", "cat": "Protéines", "kcal": 150, "p": 22.9, "c": 0, "f": 5.8},
  {"id": "boeuf-maigre", "name": "Bœuf maigre (tende de tranche) cuit", "cat": "Protéines", "kcal": 197, "p": 31.7, "c": 0, "f": 6.8},
  {"id": "poulet-tranches", "name": "Blanc de poulet Fleury Michon (tranches)", "cat": "Protéines", "kcal": 115, "p": 22, "c": 1, "f": 2.5, "unit": "tranche", "unitG": 37.5, "aliases": ["jambon de poulet"]},
  {"id": "jambon-herta", "name": "Jambon Herta Tendre Noix", "cat": "Protéines", "kcal": 112, "p": 21, "c": 0.5, "f": 2.9, "unit": "tranche", "unitG": 40, "aliases": ["jambon"]},
  {"id": "oeuf", "name": "Œuf entier", "cat": "Protéines", "kcal": 145.5, "p": 12.7, "c": 0, "f": 10.9, "unit": "œuf", "unitG": 55, "aliases": ["oeuf", "oeufs", "œufs"]},
  {"id": "blancs-oeufs", "name": "Blancs d'œufs liquides", "cat": "Protéines", "kcal": 47.6, "p": 11.1, "c": 0, "f": 0, "aliases": ["blanc d'oeuf"]},
  {"id": "fromage-blanc-0", "name": "Fromage blanc 0 %", "cat": "Produits laitiers", "kcal": 45, "p": 8, "c": 4, "f": 0, "unit": "c.à.s", "unitG": 15, "aliases": ["fromage blanc"]},
  {"id": "yaourt-grec-0", "name": "Yaourt grec 0 %", "cat": "Produits laitiers", "kcal": 57.1, "p": 10.3, "c": 3.4, "f": 0, "aliases": ["yogourt grec", "yaourt grec"]},
  {"id": "skyr", "name": "Skyr nature 0 %", "cat": "Produits laitiers", "kcal": 60, "p": 11, "c": 4, "f": 0},
  {"id": "leerdammer-ligne", "name": "Leerdammer Ligne (tranches)", "cat": "Produits laitiers", "kcal": 273, "p": 30, "c": 0.5, "f": 17, "unit": "tranche", "unitG": 20},
  {"id": "vache-qui-rit-light", "name": "Vache qui Rit Light", "cat": "Produits laitiers", "kcal": 146, "p": 12, "c": 6, "f": 8, "unit": "portion", "unitG": 17.5},
  {"id": "cheddar", "name": "Cheddar", "cat": "Produits laitiers", "kcal": 403, "p": 24.7, "c": 1.3, "f": 33.3},
  {"id": "emmental-rape", "name": "Emmental râpé", "cat": "Produits laitiers", "kcal": 370, "p": 28, "c": 0.5, "f": 29},
  {"id": "flocons-avoine", "name": "Flocons d'avoine", "cat": "Glucides", "kcal": 375, "p": 12.5, "c": 67.5, "f": 7.5, "unit": "c.à.s", "unitG": 10, "aliases": ["avoine"]},
  {"id": "creme-riz", "name": "Crème de riz (sèche)", "cat": "Glucides", "kcal": 370, "p": 6.3, "c": 82.4, "f": 0.5},
  {"id": "riz-basmati-cuit", "name": "Riz basmati cuit", "cat": "Glucides", "kcal": 132, "p": 3, "c": 31, "f": 0},
  {"id": "riz-jasmin-cuit", "name": "Riz jasmin cuit", "cat": "Glucides", "kcal": 120, "p": 3, "c": 26, "f": 0},
  {"id": "riz-complet-cuit", "name": "Riz complet cuit", "cat": "Glucides", "kcal": 110.8, "p": 2.6, "c": 23.1, "f": 1},
  {"id": "riz-rond-sec", "name": "Riz rond (sec)", "cat": "Glucides", "kcal": 355, "p": 6.5, "c": 78, "f": 0.6, "aliases": ["riz rond"]},
  {"id": "vermicelles-riz", "name": "Vermicelles de riz cuits", "cat": "Glucides", "kcal": 134, "p": 2, "c": 30, "f": 0},
  {"id": "pdt-four", "name": "Pommes de terre au four", "cat": "Glucides", "kcal": 94, "p": 2, "c": 21, "f": 0, "aliases": ["pommes de terre", "frites au four"]},
  {"id": "patate-douce", "name": "Patate douce cuite", "cat": "Glucides", "kcal": 92, "p": 2, "c": 20.6, "f": 0.1},
  {"id": "couscous-cuit", "name": "Couscous cuit", "cat": "Glucides", "kcal": 112, "p": 3.8, "c": 23.2, "f": 0.2},
  {"id": "quinoa-cuit", "name": "Quinoa cuit", "cat": "Glucides", "kcal": 120, "p": 4.4, "c": 21.3, "f": 1.9},
  {"id": "harrys-complet", "name": "Pain de mie complet Harry's American Sandwich", "cat": "Glucides", "kcal": 241, "p": 8, "c": 42.2, "f": 4.3, "unit": "tranche", "unitG": 43, "aliases": ["pain de mie complet", "harry's"]},
  {"id": "pain-multicereales", "name": "Pain multicéréales", "cat": "Glucides", "kcal": 265, "p": 13.4, "c": 43.3, "f": 4.2},
  {"id": "pain-pita", "name": "Pain pita", "cat": "Glucides", "kcal": 275, "p": 9.1, "c": 55.7, "f": 1.2, "unit": "pita", "unitG": 60},
  {"id": "pain-burger", "name": "Pain burger", "cat": "Glucides", "kcal": 250, "p": 11.7, "c": 45, "f": 3.3, "unit": "pain", "unitG": 60},
  {"id": "wrap-complet", "name": "Wrap complet (tortilla)", "cat": "Glucides", "kcal": 270, "p": 9, "c": 45, "f": 5, "unit": "wrap", "unitG": 47.5, "aliases": ["tortilla"]},
  {"id": "galette-riz", "name": "Galette de riz nature", "cat": "Glucides", "kcal": 389, "p": 11.1, "c": 77.8, "f": 0, "unit": "galette", "unitG": 9, "aliases": ["galettes de riz"]},
  {"id": "granola", "name": "Granola", "cat": "Glucides", "kcal": 444.3, "p": 9, "c": 75.7, "f": 11},
  {"id": "myrtilles", "name": "Myrtilles (bleuets)", "cat": "Fruits", "kcal": 57, "p": 1, "c": 14, "f": 0, "unit": "poignée", "unitG": 30, "aliases": ["bleuets", "myrtilles"]},
  {"id": "banane", "name": "Banane", "cat": "Fruits", "kcal": 89, "p": 0.85, "c": 22.9, "f": 0, "unit": "banane", "unitG": 118, "aliases": ["bananes"]},
  {"id": "fraises", "name": "Fraises", "cat": "Fruits", "kcal": 32, "p": 1, "c": 8, "f": 0},
  {"id": "framboises", "name": "Framboises", "cat": "Fruits", "kcal": 52, "p": 1, "c": 12, "f": 0.5},
  {"id": "mures", "name": "Mûres", "cat": "Fruits", "kcal": 42.9, "p": 0, "c": 10.7, "f": 0},
  {"id": "ananas", "name": "Ananas", "cat": "Fruits", "kcal": 50, "p": 1, "c": 13, "f": 0},
  {"id": "mangue", "name": "Mangue", "cat": "Fruits", "kcal": 65, "p": 0.5, "c": 17, "f": 0.3},
  {"id": "pomme", "name": "Pomme", "cat": "Fruits", "kcal": 52, "p": 0, "c": 13.7, "f": 0, "unit": "pomme", "unitG": 182},
  {"id": "beurre-cacahuete", "name": "Beurre de cacahuète", "cat": "Lipides", "kcal": 666.7, "p": 26.7, "c": 20, "f": 53.3, "unit": "c.à.c", "unitG": 5, "aliases": ["beurre d'arachide", "beurre de cacahuete"]},
  {"id": "beurre-amande", "name": "Beurre d'amande", "cat": "Lipides", "kcal": 633, "p": 15, "c": 21.3, "f": 59},
  {"id": "huile-olive", "name": "Huile d'olive", "cat": "Lipides", "kcal": 900, "p": 0, "c": 0, "f": 100, "unit": "c.à.c", "unitG": 5},
  {"id": "amandes", "name": "Amandes", "cat": "Lipides", "kcal": 580, "p": 22, "c": 20, "f": 50},
  {"id": "noix-cajou", "name": "Noix de cajou", "cat": "Lipides", "kcal": 553, "p": 18, "c": 32, "f": 42.7, "aliases": ["cashew"]},
  {"id": "cacahuetes", "name": "Cacahuètes grillées salées", "cat": "Lipides", "kcal": 600, "p": 25, "c": 14, "f": 49, "aliases": ["cacahuètes"]},
  {"id": "chocolat-noir-70", "name": "Chocolat noir 70 %", "cat": "Lipides", "kcal": 550, "p": 7, "c": 30, "f": 35, "unit": "carré", "unitG": 10, "aliases": ["chocolat noir"]},
  {"id": "graines-chia", "name": "Graines de chia", "cat": "Lipides", "kcal": 490, "p": 17, "c": 42, "f": 31, "unit": "c.à.c", "unitG": 5, "aliases": ["chia"]},
  {"id": "miel", "name": "Miel", "cat": "Épicerie", "kcal": 305, "p": 0, "c": 81, "f": 0, "unit": "c.à.s", "unitG": 21},
  {"id": "confiture", "name": "Confiture", "cat": "Épicerie", "kcal": 267, "p": 0, "c": 60, "f": 0, "unit": "c.à.s", "unitG": 15},
  {"id": "cacao-poudre", "name": "Cacao en poudre non sucré", "cat": "Épicerie", "kcal": 280, "p": 20, "c": 10, "f": 14, "unit": "c.à.c", "unitG": 5, "aliases": ["cacao"]},
  {"id": "speculoos", "name": "Spéculoos Lotus", "cat": "Épicerie", "kcal": 462.5, "p": 5, "c": 65, "f": 20, "unit": "biscuit", "unitG": 8, "aliases": ["speculoos"]},
  {"id": "ketchup", "name": "Ketchup", "cat": "Épicerie", "kcal": 102, "p": 1.2, "c": 23.2, "f": 0.1, "unit": "c.à.s", "unitG": 17},
  {"id": "mayo-allegee", "name": "Mayonnaise allégée", "cat": "Épicerie", "kcal": 265, "p": 0.6, "c": 6, "f": 26, "unit": "c.à.c", "unitG": 5, "aliases": ["mayo"]},
  {"id": "moutarde", "name": "Moutarde de Dijon", "cat": "Épicerie", "kcal": 150, "p": 7, "c": 4, "f": 11, "unit": "c.à.c", "unitG": 5, "aliases": ["moutarde"]},
  {"id": "oignon", "name": "Oignon", "cat": "Légumes", "kcal": 40, "p": 1.1, "c": 9, "f": 0.1, "unit": "oignon", "unitG": 110},
  {"id": "cornichons", "name": "Cornichons", "cat": "Légumes", "kcal": 25, "p": 1, "c": 4, "f": 0, "unit": "cornichon", "unitG": 5},
  {"id": "salade-iceberg", "name": "Salade iceberg", "cat": "Légumes", "kcal": 14, "p": 0.9, "c": 3, "f": 0.1, "aliases": ["salade"]},
  {"id": "legumes", "name": "Légumes (comptés à 0 par le coach)", "cat": "Légumes", "kcal": 0, "p": 0, "c": 0, "f": 0, "aliases": ["légumes"]},
  {"id": "whey-critical", "name": "Whey Critical (Applied Nutrition)", "cat": "Compléments", "kcal": 360, "p": 72, "c": 12, "f": 6, "unit": "dose", "unitG": 33, "aliases": ["whey"]},
  {"id": "isolate-dymatize", "name": "Isolate Dymatize ISO100", "cat": "Compléments", "kcal": 357, "p": 85.7, "c": 7, "f": 0, "unit": "scoop", "unitG": 30, "aliases": ["isolate"]},
  {"id": "eaa", "name": "EAA", "cat": "Compléments", "kcal": 400, "p": 100, "c": 0, "f": 0},
  {"id": "karbolyn", "name": "Karbolyn", "cat": "Compléments", "kcal": 400, "p": 0, "c": 100, "f": 0},
  {"id": "maltodextrine", "name": "Maltodextrine", "cat": "Compléments", "kcal": 380, "p": 0, "c": 95, "f": 0},
  {"id": "eau-coco", "name": "Eau de coco", "cat": "Compléments", "kcal": 19, "p": 0.73, "c": 3.7, "f": 0.2, "unit": "cup", "unitG": 240}
];
